"""Shared constants for the digitizer package."""

from __future__ import annotations

import logging

LOGGER = logging.getLogger("plot_digitizer")
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg"}
DEFAULT_X_RANGE = (0.0, 1.0)
DEFAULT_Y_RANGE = (0.0, 1.0)
MIN_COMPONENT_PIXELS = 24
PLOT_MARGIN_FRACTION = 0.02
DEFAULT_DPI = 140
DBSCAN_NOISE_LABEL = -1
MAX_DARK_THRESHOLD = 220
DARK_PIXEL_PERCENTILE = 82
BASE_CV_CONFIDENCE = 0.45
MAX_CV_CONFIDENCE = 0.99
MAX_POLYGON_POINTS = 200
CURVE_MASK_PADDING_PIXELS = 8
MAX_COLOR_CLUSTERS = 4
MAX_CLUSTER_SAMPLE_SIZE = 2000
MINIBATCH_KMEANS_BATCH_SIZE = 1024
MIN_CURVES_PER_PLOT = 1
MAX_CURVES_PER_PLOT = 3
VALIDATION_THRESHOLD = 0.05
MAX_REPLOT_POINTS = 600
MAX_REPLOT_LEGEND_DATASETS = 10
DEFAULT_GENERATE_WORKERS_CAP = 8
INTERACTIVE_CLICK_RADIUS_SCALE = 0.02
INTERACTIVE_ZOOM_HALF_SIZE_SCALE = 0.06
INTERACTIVE_ZOOM_HALF_SIZE_MIN = 24
INTERACTIVE_SELECTION_HELP_TEXT = (
    "Left click to add/select and drag points. Right click removes nearest point. "
    "Press Enter when 4 points are set (X1, X2, Y1, Y2). Press Esc to cancel."
)
INTERACTIVE_SELECTION_LIMIT_REACHED_TEXT = (
    "Already selected 4 points. Drag existing points or right-click to remove one."
)
INTERACTIVE_SELECTION_REMOVED_TEXT = (
    "Point removed. Left click to add/select and drag. Right click removes nearest point."
)
SINE_AMPLITUDE_RANGE = (0.5, 1.8)
SINE_FREQUENCY_RANGE = (0.6, 2.4)
SINE_OFFSET_RANGE = (-0.75, 0.75)
EXP_SCALE_RANGE = (0.2, 1.1)
EXP_GROWTH_RANGE = (0.15, 0.55)
EXP_OFFSET_RANGE = (-0.8, 0.3)
DAMPED_AMPLITUDE_RANGE = (0.8, 1.8)
DAMPED_DECAY_RANGE = (0.05, 0.2)
DAMPED_FREQUENCY_RANGE = (1.0, 2.6)
POLY_A_RANGE = (-0.05, 0.05)
POLY_B_RANGE = (-0.4, 0.4)
POLY_C_RANGE = (-0.8, 0.8)
NOISE_STD_RANGE = (0.01, 0.05)
DENSE_CURVE_PROBABILITY = 0.4
DENSE_CURVE_COUNT_RANGE = (4, 6)
BASE_CURVE_COUNT_RANGE = (2, 4)
VBAR_COUNT_RANGE = (1, 3)
HBAR_COUNT_RANGE = (1, 2)
ARROW_COUNT_RANGE = (0, 2)
ERROR_BAR_COUNT_RANGE = (2, 5)
CURVE_LINEWIDTHS = [0.6, 0.8, 1.0, 1.2, 1.6, 2.0]
CURVE_LINEWIDTH_PROBABILITIES = [0.28, 0.24, 0.2, 0.14, 0.09, 0.05]
GRID_ENABLED_PROBABILITY = 0.6
GRID_ALPHA = 0.4
LOG_X_PROBABILITY = 0.3
LOG_X_MIN = 0.1
ANNOTATOR_LINE_WIDTH_DEFAULT = 3.0
ANNOTATOR_CAP_WIDTH_FACTOR = 5.0
LEGEND_PROBABILITY = 0.55
ARROW_LABEL_PROBABILITY = 0.55
COLOR_INVERT_PROBABILITY = 0.22
ARROW_LABEL_TEXTS = ["ΔE", "α", "ref.", "peak", "onset", "gap", "Δ", "onset", "E_F"]
